### PR TITLE
Response data format

### PR DESCRIPTION
**Pull request by vetlewi**
I've added a class for reading the files required to perform the response matrix interpolation. I'm not sure if it should be pulled yet.

The class has a static method `interpolate_response` that will give return the same response matrix as the old `interpolate_response` does, but will also return the `Response` object if the correct flag is set. The  `Response` class currently implements a method to read a folder just as the old `interpolate_response` or it can read a zip-file with (almost) the same files. In the case of the zip-file it will not look for the `resp.dat` file but for `resp.csv` instead. The `resp.csv` file has to contain at least the same columns as `resp.dat`, but could include more if needed later. I've attached an [example zip file](https://github.com/oslocyclotronlab/ompy/files/3718385/oscar2017_scale1.15.zip). With this format it should be fairly straight forward to add new response functions

### CODE REVIEW

**Comment by fzeiser** [comment]
I'll have a look at it next week. The interpolate response function was anyhow not cleaned up nicely yet. So it nice that you started on this!

**Comment by fzeiser** [comment]
I also think it's good to to put the response in some repo. I suggest to rename https://github.com/oslocyclotronlab/oscar_response to `response_functions` and place the response itself there.

**Comment by fzeiser** [comment]
Can you add dockstrings for the arguments ant returns? It'd also be nice to clean up and refactor the `interpolate` method, as it it really way too long. But it's not on the top of my priority list. So it depends a bit on how much time you might want to send with it :nerd_face: .

**Comment by vetlewi** [comment]
> Can you add dockstrings for the arguments ant returns? It'd also be nice to clean up and refactor the `interpolate` method, as it it really way too long. But it's not on the top of my priority list. So it depends a bit on how much time you might want to send with it 🤓 .

I can add docstrings. I don't know if I want to spend too much more time on this at the moment. Was primarily so that I could easily add response functions myself. I'll see what I have time for.

**Comment by vetlewi** [comment]
> Can you add dockstrings for the arguments ant returns? It'd also be nice to clean up and refactor the `interpolate` method, as it it really way too long. But it's not on the top of my priority list. So it depends a bit on how much time you might want to send with it 🤓 .



> I also think it's good to to put the response in some repo. I suggest to rename https://github.com/oslocyclotronlab/oscar_response to `response_functions` and place the response itself there.

Sounds like a great idea!

**Comment by fzeiser** [comment]
Further treated in #65, as I was missing push -f rights

**Pull request closed without merging**
