### PR TITLE
Fixed an error in the calculation of the rho(Sn). Fixing issue #90

### PR DESCRIPTION
**Pull request by vetlewi**

### CODE REVIEW

**Comment by fzeiser** [comment]
How about adding something like this in the docstring? Just that 
> See issue #90 for derivation/discussion

**Comment by fzeiser** [comment]
Just a comment on the plotting you've had there before you reverted:
I think it makes more sense to plot as a histogram if you don't smooth, Once you smooth, we can just as well plot it as a line - I think. but that's easy to fix for people

**Comment by vetlewi** [comment]
> Just a comment on the plotting you've had there before you reverted:
> I think it makes more sense to plot as a histogram if you don't smooth, Once you smooth, we can just as well plot it as a line - I think. but that's easy to fix for people

Probably the easiest will be to add a keyword argument like `disc_kind`. Something for another PR!

**Comment by fzeiser** [comment]
Yep, sth for another PR. But we want to avoid adding lot's of keyword. At some point, it's easier if people just adopt the part of the code they want to have adopted

**Comment by vetlewi** [comment]
> Yep, sth for another PR. But we want to avoid adding lot's of keyword. At some point, it's easier if people just adopt the part of the code they want to have adopted

I agree. One just need to make a good interface to modify such things without having to dive too far down into the codebase. Maybe the user should make a subclass where the subclass will reimplement the `plot` method?

**Comment by fzeiser** [comment]
Sounds good, yep, lets have another PR with an example for people on how to modify...

**Pull request merged**
