### PR TITLE
Travis ci

### PR DESCRIPTION
**Pull request by vetlewi**
I've updated the Travis-CI configuration file. This should close issue #56. Note that the build itself fails in the test. There are some missing files required by the test causing the build fail.
See https://travis-ci.com/vetlewi/ompy for results from my branch

### CODE REVIEW

**Comment by fzeiser** [comment]
It fails due to (py)multinest:
```
==================================== ERRORS ====================================

______________________ ERROR collecting test_firstgen.py _______________________

deps/PyMultiNest/pymultinest/run.py:23: in <module>

    lib = cdll.LoadLibrary(libname)

/opt/python/3.7.1/lib/python3.7/ctypes/__init__.py:434: in LoadLibrary

    return self._dlltype(name)

/opt/python/3.7.1/lib/python3.7/ctypes/__init__.py:356: in __init__

    self._handle = _dlopen(self._name, mode)

E   OSError: .so: cannot open shared object file: No such file or directory

During handling of the above exception, another exception occurred:

tests/test_firstgen.py:3: in <module>

    import ompy as om

ompy/__init__.py:40: in <module>

    from .multinest_setup import *

ompy/multinest_setup.py:5: in <module>

    import pymultinest

deps/PyMultiNest/pymultinest/__init__.py:19: in <module>

    from .run import run

deps/PyMultiNest/pymultinest/run.py:58: in <module>

    sys.exit(1)

E   SystemExit: 1

------------------------------- Captured stdout --------------------------------

ERROR:   Could not load MultiNest library ".so"

ERROR:   You have to build it first,

ERROR:   and point the LD_LIBRARY_PATH environment variable to it!

ERROR:   manual: http://johannesbuchner.github.com/PyMultiNest/install.html

ERROR:   Could not load MultiNest library: .so

ERROR:   You have to build MultiNest,

ERROR:   and point the LD_LIBRARY_PATH environment variable to it!

ERROR:   manual: http://johannesbuchner.github.com/PyMultiNest/install.html

problem: .so: cannot open shared object file: No such file or directory
```

**Comment by fzeiser** [comment]
@vetlewi: Sorry, I pushed the changes to your branch instead of my own fork. Anyhow, I'll see whether this fixes it.

**Comment by fzeiser** [comment]
Fixed it now, I'll upload soon

**Comment by vetlewi** [comment]
If you move the building of the dependencies to `before_install` it will fail... Dont know why... Everything needs to be done in `install`

**Comment by fzeiser** [comment]
I'm not breaking it, I make it work ;P. Look at this beautiful travis report that will come here.

**Comment by fzeiser** [comment]
Any further issues with this? I think it works beautifully...

**Pull request merged**
